# Setup | team_g
# 
# For "setuptools" only
# 
# 2020-11-19
# 
# ***
# 
# Generated by Readme Parser
# 
# +++
# Description
# 
# An auto-generated setup file for team_g by Readme Parser. Remember to fill/add any other fields, as needed. For more information, read the Readme Parser readme and/or in-module documentation.
# 
# +++
# Imports
# 
from setuptools import setup
# 
# +++
# Output
# 
setup(
	long_description = """""",
	name = """Team G""",
	version = """""",
	url = """""",
	description = """Readme Parser | WTCC CSC 130 Group Project""",
	release_date = """""",
	download_url = """https://github.com/bizzlebin/team_g/""",
	license = """""",
	author = """By Jeremiah Thomas, et al""",
	license_file = """***

Created 2020-11-16

***

Copyright © Jeremiah Thomas, et al

All rights reserved. All copyright holders retain full copyright individually and may sublicense the work, up to and including a Ø (CC0) declaration.

"""THE WORK IS PROVIDED "AS IS" AND THE AUTHORS AND OWNERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS WORK INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHORS OR OWNERS BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS WORK."""""",
	long_description_content_type = """text/plain""",
	py_modules = ["""team_g""",],
)