# Setup | readme_parser_0.3.0make_setup.py_easyhttpsgithub.combizzlebinteam_g
# 
# For "setuptools" Only
# 
# ***
# 
# By {author}
# 
# Generated by Readme Parser
# 
# ***
# 
# Created 2020-11-25
# 
# +++
# Description
# 
# An auto-generated setup file for readme_parser_0.3.0make_setup.py_easyhttpsgithub.combizzlebinteam_g by Readme Parser. Remember to fill/add any other fields, as needed. For more information, read the Readme Parser readme and/or in-module documentation.
# 

# 
# +++
# Imports
# 
from setuptools import setup
# 
# +++
# Output
# 
setup(
	long_description = """A basic parser to extract setup.py metadata fields from a NKMF-compliant (and UEWSG-compliant!) UTF-8 readme file.""",
	Title = """Readme Parser 0.3.0

Make "setup.py" Easy!

https://github.com/bizzlebin/team_g/""",
	Authorship = """By Jeremiah Thomas, et al""",
	Timestamps = """Created 2020-04-16

Updated 2020-11-20""",
	Usage = """Copyright © Jeremiah Thomas, et al

All rights reserved. All copyright holders retain full copyright individually and may sublicense the work, up to and including a Ø (CC0) declaration.

"""THE WORK IS PROVIDED "AS IS" AND THE AUTHORS AND OWNERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS WORK INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHORS OR OWNERS BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS WORK."""""",
	Description = """Description

A basic parser to extract setup.py metadata fields from a NKMF-compliant (and UEWSG-compliant!) UTF-8 readme file.""",
	name = """Readme Parser""",
	version = """0.3.0""",
	url = """""",
	description = """Make "setup.py" Easy!""",
	release_date = """""",
	download_url = """https://github.com/bizzlebin/team_g/""",
	license = """""",
	author = """By Jeremiah Thomas, et al""",
	license_file = """***

Created 2020-04-16

Updated 2020-11-20

***

Copyright © Jeremiah Thomas, et al

All rights reserved. All copyright holders retain full copyright individually and may sublicense the work, up to and including a Ø (CC0) declaration.

"""THE WORK IS PROVIDED "AS IS" AND THE AUTHORS AND OWNERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS WORK INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHORS OR OWNERS BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS WORK."""""",
	long_description_content_type = """text/plain""",
	py_modules = ["""readme_parser_0.3.0make_setup.py_easyhttpsgithub.combizzlebinteam_g""",],
)