# Setup | readme_parser
# 
# For "setuptools" Only
# 
# ***
# 
# By {author}
# 
# Generated by Readme Parser
# 
# ***
# 
# Created 2020-12-03
# 
# +++
# Description
# 
# An auto-generated setup file for readme_parser by Readme Parser. Remember to fill/add any other fields, as needed. For more information, read the Readme Parser readme and/or in-module documentation.
# 

# 
# +++
# Imports
# 
from setuptools import setup
# 
# +++
# Output
# 
setup(
	name = """Readme Parser""",
	version = """0.3.0""",
	url = """https://github.com/bizzlebin/team_g/""",
	description = """Make "setup.py" Easy!""",
	download_url = """""",
	author = """Jeremiah Thomas, et al""",
	author_email = """""",
	copyright = """""",
	license = """Copyright © Jeremiah Thomas, et al""",
	long_description = """A basic parser to extract setup.py metadata fields from a NKMF-compliant (and UEWSG-compliant!) UTF-8 readme file.""",
	long_description_content_type = """text/plain""",
	py_modules = ["""readme_parser""",],
)