# Setup | readme
#
# For "setuptools" only
#
# 2020-11-22
#
# ***
#
# Generated by Readme Parser
#
# +++
# Description
#
# An auto-generated setup file for readme by Readme Parser. Remember to fill/add any other fields, as needed. For more information, read the Readme Parser readme and/or in-module documentation.
#
# +++
# Imports
#
from setuptools import setup
#
# +++
# Output
#
setup(
	name = """readme""",
	version = """""",
	url = """""",
	description = """""",
	release_date = """""",
	download_url = """https://github.com/bizzlebin/team_g/blob/master/resources/readme.txt""",
	license = """""",
	author = """By Jeremiah Thomas""",
	license_file = """***

Created 2020-05-24

Updated 2020-11-16""",
	long_description = """""",
	long_description_content_type = """text/plain""",
	py_modules = ["""readme""",],
)